### ISSUE TITLE
Can't download spring-boot-thin-launcher from a local mirror

### ISSUE THREAD

**Issue by alexfdezsauco** [dsyer/spring-boot-thin-launcher#60] opened 2018-09-03 16:04 UTC
I'm trying to force download the launcher from a local mirror using `thin.repo` key (from the sources)

mvn package -Dthin.repo=http://nexus.local/repository/maven-public/ 

but doesn't work. Always try to download from repo.spring.io.

I also have a custom settings.xml in .m2 but is ignore or overriding by launcher pom.

In the sources, it looks like it could use thin.repo property but is ignored.

Any suggestion.

**Comment by dsyer** [comment] 2018-09-03 21:12
I'm not really sure what you were trying to do there: `mvn package` is a Maven thing, nothing to do with this project. The `thin.*` properties only kick in if you are actually using the thing launcher.

**Comment by dsyer** [comment] 2018-09-04 12:31
Still a bit thin on detail. Can we see the pom.xml and the relevant sections from settings.xml?

**Comment by alexfdezsauco** [comment] 2018-09-04 13:11
Here is the mirror section

%HOME%\.m2\settings.xml 

 <mirrors>
        <mirror>
            <id>nexus</id>
            <mirrorOf>*</mirrorOf>
            <name>Local Nexus Sonatype  Repository Mirror</name>
            <url>http://localhost:8081/repository/maven-public/</url>
        </mirror>
....

**Comment by dsyer** [comment] 2018-09-04 13:35
And the project pom? I don't think `mvn package` downloads the launcher by default. You have to configure something.

**Comment by alexfdezsauco** [comment] 2018-09-04 14:05
pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <java.version>1.8</java.version>
	<wrapper.version>1.0.14.RELEASE</wrapper.version>
    </properties>

    <groupId>ensemble.jobs</groupId>
    <artifactId>ensemble-jobs-eat-from-lstm</artifactId>
    <version>0.1.0</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.0.M2</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.1.0.M2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>${wrapper.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			
			<plugin>
				<groupId>org.springframework.boot.experimental</groupId>
				<artifactId>spring-boot-thin-maven-plugin</artifactId>
				<version>${wrapper.version}</version>
				<executions>
					<execution>
						<id>resolve</id>
						<goals>
							<goal>resolve</goal>
						</goals>
						<inherited>false</inherited>
					</execution>
				</executions>
			</plugin>
        </plugins>
    </build>
</project>
```

**Comment by dsyer** [comment] 2018-09-04 14:11
Right, so you are using the `spring-boot-thin-maven-plugin`. That was useful to know. Is the launcher already cached locally when the plugin runs?

Maybe you can work around it just by adding the launcher exec jar as a dependency of the thin-maven-plugin?

**Comment by alexfdezsauco** [comment] 2018-09-04 14:27
That was my first thought but, but thin always try to download `spring-boot-thin-launcher-1.0.14.RELEASE-exec.jar` first from internet. The build machine has no internet access and it requires to download the dependencies from our local mirror.

The my "workaround" was add this `target\thin\root\repository\org\springframework\boot\experimental\spring-boot-thin-launcher\1.0.14.RELEASE\spring-boot-thin-launcher-1.0.14.RELEASE-exec.jar`  to the version control.

With all artifacts cached including this one declared as a dependency of the plugin

```
		<dependency>
			<groupId>org.springframework.boot.experimental</groupId>
			<artifactId>spring-boot-thin-launcher</artifactId>
			<version>${wrapper.version}</version>
			<classifier>exec</classifier>
		</dependency>
```
I got this error:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot locate library: ./repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.14.RELEASE/spring-boot-thin-launcher-1.0.14.RELEASE-exec.jar
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:121)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:98)
```

**Comment by dsyer** [comment] 2018-09-04 15:09
I can see there might be a problem, but it's really not clear yet how to reproduce it or test it. Can you come up with a project that demonstrate's the issue in some way?

**Comment by alexfdezsauco** [comment] 2018-09-04 16:28
Here is a log of `mvn package` in a "disconnected" with a settings.xml as I show you before. Notice the direct request to https://repo.spring.io/libs-snapshot.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:126)
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:98)
Caused by: java.lang.RuntimeException: Could not transfer artifact org.eclipse.collections:eclipse-collections-api:jar:7.1.2 from/to spring-snapshots (https://repo.spring.io/libs-snapshot): Connection refused: connect
Could not transfer artifact org.eclipse.collections:eclipse-collections:jar:7.1.2 from/to spring-snapshots (https://repo.spring.io/libs-snapshot): Connection refused: connect
        at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:225)
        at org.springframework.boot.loader.thin.PathResolver.extract(PathResolver.java:211)
        at org.springframework.boot.loader.thin.PathResolver.resolve(PathResolver.java:99)
        at org.springframework.boot.loader.thin.ThinJarLauncher.getClassPathArchives(ThinJarLauncher.java:326)
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:187)
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:139)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.028 s
[INFO] Finished at: 2018-09-04T12:24:43-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by dsyer** [comment] 2018-09-04 16:54
Can you help to reproduce the issue in a controlled environment, please? A sample project with instructions on how to make it fail would be ideal.

**Comment by alexfdezsauco** [comment] 2018-09-04 17:51
Here is the description of the controlled environment:

1. docker run sonatype/nexus3:3.13.0 -p:8081:8081
2. use this file as settings.xml in %USER_PROFILE%\\.m2
```
<settings 
    xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <mirrors>
        <mirror>
            <id>nexus</id>
            <mirrorOf>*</mirrorOf>
            <name>Local Nexus Sonatype  Repository Mirror</name>
            <url>http://localhost:8081/repository/maven-central/</url>
        </mirror>
    </mirrors>
</settings>
```
by default nexus3 comes with a mirror of maven central.

3. Ensure that your build process (java.exe) has no internet to any maven internet repository. You can use proxifier https://www.proxifier.com/ for this and block specific request of a specific process. 

4. Use any spring boot quickstart sample but use thin maven configuration to build a thin jar.

5. run mvn package.

Expected results:
- All dependencies should be downloaded from the local nexus

Current behavior:
- Some dependencies requests are done directly to a maven internet repository (e.g: https://repo.spring.io/libs-snapshot) instead of use (or respect) the current settings.xml. Therefore the build failed because java process have no internet access.

**Comment by dsyer** [comment] 2018-09-04 21:15
Thanks, I’ll try that with the pom.xml you posted earlier. 

You said "use thin maven configuration to build a thin jar”, so I just wanted to make sure you were aware that you can build a thin jar without the thin-maven-plugin. What is your intended end state?

**Comment by dsyer** [comment] 2018-09-05 13:06
A thin jar is executable but not self-contained. If that's what you want you don't need the thin-maven-plugin (just the layout in the Spring Boot plugin). You can build the jar and execute it as above.

But if your main focus is building a custom docker container, and you don't need multiple containers with different classpaths, I would just use the regular Spring Boot fat jar, if I were you. The application code is in `BOOT-INF/classes` and the dependencies are in `BOOT-INF/lib` so it's easy to create efficient file system layers. I don't know what the thin launcher would give you in that scenario that would be of use.

**Comment by dsyer** [comment] 2018-09-05 13:42
You need the layout (like you already had in your pom):

```
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>${wrapper.version}</version>
					</dependency>
				</dependencies>
			</plugin>
```

**Comment by alexfdezsauco** [comment] 2018-09-05 14:26
Great, so I didn't miss anything.  
```
<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>${wrapper.version}</version>
					</dependency>
				</dependencies>
			</plugin>
```
only got a thin jar but without depedencies. I need the depdencies so, as I understood I need to use `spring-boot-thin-maven-plugin` to build the .m2  like directory (thin/repository) with the dependencies. So, I also need the launcher.

The only issue is that I can't build the layout because "some" dependencies are downloading from the internet (not from the local mirror as I expected).

**Comment by dsyer** [comment] 2018-09-05 16:14
That's not really a workaround: that's the best way to build a single fixed docker container for a Spring Boot app. It would start quicker if you used the main class instead of the `JarLauncher`, but that's irrelevant for the file system layers.

**Comment by dsyer** [comment] 2018-09-05 16:21
Also, back to the original problem, AFAIK the launcher should be fetched from the local cache if there is one, so adding it to the dependencies in the plugin should work. The most recent comment from you with an actual error message refers not to the launcher but to `org.eclipse.collections:eclipse-collections`, which shouldn't be downloaded by the launcher. Maybe your project depends on it? So we are still struggling top reproduce the actual issue.

**Comment by alexfdezsauco** [comment] 2018-09-05 17:17
> AFAIK the launcher should be fetched from the local cache

All dependencies are in the local cache.

> org.eclipse.collections:eclipse-collections, which shouldn't be downloaded by the launcher. Maybe your project depends on it?

Yes, actually it builds without this plugin. So, all dependencies are in the local cache downloaded from the local mirror. But when I want to use the plugin, it tries to download some dependencies from internet, instead of copy from the local cache or respect the settings.xml to download from the local mirror.

**Comment by dsyer** [comment] 2018-09-05 17:31
> But when I want to use the plugin, it tries to download some dependencies from internet

That's the bit that doesn't make sense to me.

I have a plan to try and isolate the build from the mirror using docker containers. I'm not really very confident I know what I'm doing with docker networks, so it might take some time. If you have a way to do it, please elaborate to speed me up.

**Comment by dsyer** [comment] 2018-09-06 07:51
That's a better docker strategy TBH than using the thin launcher (but as I said above you can improve it by using the application main class).

I have reproduced the original issue. It's incredibly fiddly to get the networks set up, but it is possible. I'm not sure I could automate it, but I can probably document it at least.

FWIW I could run `mvn package` on the `simple` sample, and it would build a thin (executable) jar and then fail on the `thin-maven-plugin`. Here's the error:

```
...
[ERROR] Failed to execute goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:1.0.14.RELEASE:resolve (resolve) on project simple: Execution resolve of goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:1.0.14.RELEASE:resolve failed.: NoSuchElementException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot.experimental:spring-boot-thin-maven-plugin:1.0.14.RELEASE:resolve (r...
...
Caused by: java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at org.springframework.boot.experimental.maven.ThinJarMojo.resolveFile(ThinJarMojo.java:84)
	at org.springframework.boot.experimental.maven.ResolveMojo.execute(ResolveMojo.java:102)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 28 more
```

The executable jar is also not executable until the launcher is cached locally. To do that (which would be another workaround for you), you can specify `--thin.repo=http://<your-mirror>` on the command line when you run it. I think to close this issue we need a way to do that in the Maven plugin as well.

**Closed** 2018-09-06 10:54 UTC
